### PR TITLE
Add PLO6 evaluator #34

### PR DESCRIPTION
**Pull request by HenryRLee**

### CODE REVIEW

**Comment by azriel1rf** [comment]
That sounds fantastic! I'll take the initiative to implement this feature in Python. Looking forward to integrating it into our project.

**Comment by HenryRLee** [comment]
Thanks @azriel1rf for your help!

**Comment by HenryRLee** [comment]
The CI failed probably due to compiling the table file runs out of memory.

**Comment by HenryRLee** [comment]
In the Github action script, exclude PLO6, because the compiling runs out of the 500Mb memory limit.

**Comment by HenryRLee** [comment]
To include the PLO5 and PLO6 library, use this cmake option:
```
cmake -DBUILD_PLO5=ON -DBUILD_PLO6=ON ..
```

**Pull request merged**
