### PR TITLE
Configure pre-commit hooks and GitHub Actions

### PR DESCRIPTION
**Pull request by azriel1rf**
This Pull Request introduces several changes to improve the project's code quality assurance processes and refactor the CI workflows.

# Python Formatting and Linting
- Removed `Black` and `isort` and added `Ruff` for Python linting/formatting
- Configured Ruff, mypy in `pyproject.toml`

# C++ Formatting
- Added `.clang-format` for C++ formatting based on Google style (discussed on #97)

# Pre-commit Hooks
- Set up pre-commit hooks via `.pre-commit-config.yaml`
  - General file checks (trailing whitespace, EOF, etc)
  - Formatting for TOML, YAML, markdown files
  - C++ linting & formatting with clang-format
  - Python linting with Ruff, formatting with Ruff, type checking with mypy, unit testing

# GitHub Actions Refactoring
- Updated `ci.yml` 
  - Updated versions of `actions/checkout` and `actions/setup-python`
  - Added separate jobs for Python type checking and package installation testing
- Created `pre-commit.yml` to run pre-commit checks in CI
- Added `dependabot.yml` to keep GitHub Action versions up-to-date

### Benefits
These changes offer several benefits:
- Automated checks to catch code quality issues early in the development process
- Consistent styling and best practices enforced across the codebase
- Reduced back-and-forth in code reviews by addressing common issues automatically
- Improved CI pipeline with dedicated jobs for different aspects of the project

Developers can run the pre-commit hooks locally to identify and fix problems before committing, leading to a smoother development experience and a more stable codebase.

Please review the changes and provide any feedback or suggestions. Let's work together to enhance our code quality and streamline our development process!

### CODE REVIEW

**Comment by azriel1rf** [comment]
I noticed that some files are currently blocked by the pre-commit hooks. To resolve these issues and ensure a smooth merge, I have made the necessary changes in separate pull requests:

1. #94
   - Addresses issues with python/setup.cfg

2. #96
   - Fixes trailing whitespace in Documentation/Algorithm.md
   - Ensures proper end of file for python/README.md and Documentation/Algorithm.md

3. #97
   - Removes trailing whitespace in C files
   - Fixes end of file issues in C and C++ files
   - Converts CRLF to LF line endings
   - Replaces tabs with spaces in C and C++ files

4. #100 
5. #101

Please review and merge these pull requests first. Once they are merged, the pre-commit hooks should pass successfully for this pull request.

If there are any further issues or if you have any suggestions for improving the pre-commit hooks or GitHub Actions workflow, please let me know. I'm open to feedback and collaboration to enhance our development process.

Thank you for your attention to code quality and for setting up these valuable tools!

**Review by HenryRLee — COMMENTED** [review]
Thanks for introducing this linter tool to the workflow. It looks awesome!

I have a question, is there a way to show the code diff in the workflow log output? Currently I cannot find the diff in this [workflow log](https://github.com/HenryRLee/PokerHandEvaluator/actions/runs/8934406272/job/24541300270?pr=95).

I don't expect many contributors would download `pre-commit` tool and run it locally. Of course, we can add some instructions in `CONTRIBUTING.md` to guide them, but it still creates additional barriers for them. So relying on the workflow logs may be an easier way for them. Well, if contributors are really stuck in passing the linter check, in the end, as maintainers we may have to step up to help them, e.g. show them the mistake in code review, or even commit a fix for them.

Also, we may add some more info in the `CONTRIBUTING.md` file, to ask contributors follow the [Google C++ coding style guide](https://google.github.io/styleguide/cppguide.html), and the corresponding Python coding style guide (is it https://peps.python.org/pep-0008 ?).

**Comment by azriel1rf** [comment]
The pre-commit hooks failed with exit code 143 when executing clang-format on large files, as seen in the GitHub Actions logs:

> Error: Process completed with exit code 143.

https://github.com/HenryRLee/PokerHandEvaluator/actions/runs/8934731565/job/24542074363?pr=95#step:4:145

This issue is likely caused by a crash due to insufficient resources, as discussed in actions/runner-images#6680.

To resolve this problem, I will:

1. Reset the formatting on the affected large files to their original state.
2. Update the pre-commit hook configuration to exclude these large files from linting and formatting.

By excluding the large files, we can ensure that the pre-commit hooks run successfully without encountering resource limitations.

**Comment by azriel1rf** [comment]
Thank you for sharing your thoughts and concerns regarding the pre-commit hooks and contributor experience.

I agree that we shouldn't force every contributor to use pre-commit locally, as it may create additional barriers for them. To make the process easier, I will enable verbosity for all pre-commit hooks in the GitHub Actions workflow. This will display the code diff and highlight the specific areas where the code fails to meet the style guidelines. Contributors can then refer to the workflow logs to identify and fix the issues without needing to run pre-commit locally.

Regarding the coding style guides, I suggest we update the `CONTRIBUTING.md` file to include the following information:

*  For C++, follow the Google C++ Style Guide as we disucssed
*  For Python, adhere to the Black code style, which is mostly a subset of PEP 8 with a maximum line length of 88 characters instead of 79 (as specified in PEP 8). More details can be found in the Black documentation: https://black.readthedocs.io/en/stable/the\_black\_code\_style/current\_style.html
* For Markdown, follow the markdownlint rules (https://github.com/DavidAnson/markdownlint). However, as this rule is less prevalent, we can consider omitting this guideline.
* For YAML and TOML files, ensure that the syntax is valid and well-formatted.

By providing clear guidelines in the `CONTRIBUTING.md` file, we can help contributors understand the project's coding style expectations and reduce the likelihood of style-related issues in their pull requests.

I appreciate your input and collaboration in improving the contributor experience.

**Comment by HenryRLee** [comment]
That sounds good! Thanks for the efforts!

**Comment by azriel1rf** [comment]
After rebasing, the fiels not modified are excluded from pre-commit.

**Comment by azriel1rf** [comment]
> After rebasing, the fiels not modified are excluded from pre-commit.

This was my mistaken.

**Comment by azriel1rf** [comment]
With merging #100 and #101, the pre-commit successed.
https://github.com/HenryRLee/PokerHandEvaluator/actions/runs/8948554069/job/24581813056?pr=95
I will revert merges and push this branch again.

**Comment by azriel1rf** [comment]
@HenryRLee I've made the following changes based on your review:

* Added a `git diff` step in the pre-commit configuration to display the differences between the original and formatted code. This will provide contributors with clear guidance on where and how to format their code, even if they don't run pre-commit locally.

* Updated the `CONTRIBUTING.md` file to include detailed explanations of the code styles, formatters, linters, building, and testing processes for both C++ and Python.

* Added a section in `CONTRIBUTING.md` to explain the GitHub Actions workflow, including the various checks and tests performed for each pull request. This will give contributors a better understanding of the automated processes.

* Expanded the contributing section in `python/README.md` to cover code styles, development setup, and the use of pre-commit hooks.

Please let me know if you have any further suggestions or concerns. I'm happy to improve the contribution experience for everyone involved.

**Review by HenryRLee — APPROVED** [review]
Looks great! The guidelines are very detail. Many thanks for your efforts!

**Pull request merged**
